#!/bin/bash

cat 03* | awk '{print $1,$2,$5,$6}' | grep 05:00:00 | grep AM
cat 03* | awk '{print $1,$2,$5,$6}' | grep 08:00:00 | grep AM
cat 03* | awk '{print $1,$2,$5,$6}' | grep 02:00:00 | grep PM
cat 0310_Dealer_schedule 0312_Dealer_schedule | awk '{print $1,$2,$5,$6}' | grep 08:00:00 | grep PM
cat 0310_Dealer_schedule 0312_Dealer_schedule | awk '{print $1,$2,$5,$6}' | grep 11:00:00 | grep PM

